[plugin]
repository = "https://github.com/MidoriKami/WondrousTailsSolver.git"
owners = ["daemitus", "MidoriKami", "nathanctech"]
project_path = "WondrousTailsSolver"
commit = "31630fea5681df316e0eead56d503faa4caa1fc6"
version = "3.2.2.5"
